version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test

workflows:
  nsfw-ci:
    jobs:
      - lint
      - test
